agent: ppo
model: gru
d_model: 128
n_layers: 1
d_actor: 128
d_critic: 128
num_envs: 8
rollout_len: 256
anneal_lr: false
gamma: 0.99
gae_lambda: 0.95
num_minibatches: 8
update_epochs: 4
norm_adv: true
clip_coef: 0.1
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
target_kl:
reset_on_terminate: true
optimizer: 
  learning_rate: 0.0002